from django.shortcuts import render
from django.http import HttpResponse
from chatterbot import ChatBot
from chatterbot.trainers import ChatterBotCorpusTrainer, ListTrainer

# Inicializar el chatbot
bot = ChatBot('chatbot', read_only=False, logic_adapters=[
    {
        'import_path': 'chatterbot.logic.BestMatch',
        'default_response': 'Lo siento, no entiendo tu pregunta',
        'maximum_similarity_threshold': 0.90
    }
])

# Entrenar el chatbot con corpus de texto en español
corpus_trainer = ChatterBotCorpusTrainer(bot)
corpus_trainer.train('chatterbot.corpus.spanish')

# Lista de preguntas y respuestas
preguntas_respuestas = [
'¿Qué significa ITTG?', 'El ITTG es el Instituto Tecnológico de Tuxtla Gutiérrez, una institución educativa en México que ofrece programas de educación superior en ingeniería y tecnología.',
'¿Cuáles son las carreras que ofrece el ITTG?', 'El ITTG ofrece carreras como Ingeniería en Sistemas Computacionales, Ingeniería Electrónica, Ingeniería en Gestión Empresarial, Ingeniería Industrial y más. Puedes encontrar una lista completa de las carreras en el siguiente enlace: Enlace a la lista de carreras.',
'¿Cuáles son los requisitos de admisión al ITTG?', 'Los requisitos de admisión pueden variar según la carrera y la convocatoria, pero generalmente incluyen haber concluido el nivel medio superior, presentar el examen de admisión y cumplir con los requisitos establecidos por la institución. Puedes encontrar información más detallada sobre los requisitos de admisión en el siguiente enlace: Enlace a los requisitos de admisión.',
'¿Cuál es la dirección del ITTG?', 'La dirección del ITTG es: Dirección del ITTG.',
'¿Cuál es el número de teléfono del ITTG?', 'El número de teléfono del ITTG es: Número de teléfono del ITTG.',
'¿Cuáles son las instalaciones y recursos disponibles en el ITTG?', 'El ITTG cuenta con laboratorios equipados, biblioteca, áreas deportivas, sala de cómputo, sala de conferencias, entre otros recursos para apoyar la formación de los estudiantes. Puedes obtener más información sobre las instalaciones y recursos en el siguiente enlace: Enlace a las instalaciones y recursos del ITTG.',
'¿Cuál es el horario de clases en el ITTG?', 'El horario de clases puede variar según el semestre y la carrera. Los horarios son programados por la institución y se asignan a los estudiantes. Es recomendable consultar directamente con el ITTG para obtener información actualizada sobre el horario de clases.',
'¿El ITTG ofrece programas de intercambio estudiantil?', 'Sí, el ITTG cuenta con programas de intercambio estudiantil que permiten a los estudiantes tener una experiencia de estudio en otras instituciones nacionales e internacionales. Puedes obtener más información sobre los programas de intercambio estudiantil en el siguiente enlace: Enlace a los programas de intercambio estudiantil del ITTG.',
'¿Cuál es el proceso para solicitar una beca en el ITTG?', 'El ITTG cuenta con diferentes programas de becas y apoyos financieros para los estudiantes. El proceso de solicitud puede variar según el tipo de beca, pero generalmente implica llenar una solicitud, cumplir con los requisitos establecidos y participar en el proceso de selección. Puedes obtener más información sobre las becas disponibles y el proceso de solicitud en el siguiente enlace: Enlace a las becas del ITTG.',
'¿El ITTG ofrece servicios de apoyo académico?', 'Sí, el ITTG ofrece servicios de apoyo académico como tutorías, asesorías y talleres para ayudar a los estudiantes en su proceso de aprendizaje. Además, los estudiantes pueden contar con el apoyo de los docentes y coordinadores de carrera. Puedes obtener más información sobre los servicios de apoyo académico en el siguiente enlace: Enlace a los servicios de apoyo académico del ITTG.',
'¿El ITTG tiene programas de prácticas profesionales?', 'Sí, el ITTG cuenta con programas de prácticas profesionales que permiten a los estudiantes adquirir experiencia laboral en empresas e instituciones relacionadas con su carrera. Las prácticas profesionales son una parte importante de la formación académica en el ITTG. Puedes obtener más información sobre los programas de prácticas profesionales en el siguiente enlace: Enlace a los programas de prácticas profesionales del ITTG.',
'¿El ITTG cuenta con actividades extracurriculares?', 'Sí, el ITTG ofrece una variedad de actividades extracurriculares como clubes, grupos estudiantiles, eventos deportivos, culturales y sociales. Estas actividades brindan a los estudiantes la oportunidad de desarrollar habilidades, interactuar con otros estudiantes y enriquecer su experiencia universitaria. Puedes obtener más información sobre las actividades extracurriculares en el siguiente enlace: Enlace a las actividades extracurriculares del ITTG.',
'¿Cuál es la oferta educativa del ITTG?', 'El ITTG ofrece programas de educación superior en diversas áreas como Ingeniería en Sistemas Computacionales, Ingeniería Electrónica, Ingeniería en Gestión Empresarial, Ingeniería Industrial, Ingeniería Mecatrónica, Ingeniería en Innovación Agrícola Sustentable, y más. Puedes encontrar información detallada sobre la oferta educativa en el siguiente enlace: Enlace a la oferta educativa del ITTG.',
'¿Cuál es el perfil de los egresados del ITTG?', 'Los egresados del ITTG se caracterizan por tener una formación sólida en su área de estudio, habilidades técnicas y prácticas, capacidad de trabajo en equipo, liderazgo, pensamiento crítico y habilidades para resolver problemas. Están preparados para enfrentar los retos del mundo laboral y contribuir al desarrollo de la sociedad. Puedes obtener más información sobre el perfil de los egresados en el siguiente enlace: Enlace al perfil de los egresados del ITTG.',
'¿El ITTG cuenta con convenios de colaboración con empresas?', 'Sí, el ITTG tiene convenios de colaboración con empresas e instituciones del sector público y privado. Estos convenios permiten establecer vínculos para realizar proyectos conjuntos, prácticas profesionales, programas de capacitación y más. Estos lazos con el sector empresarial brindan oportunidades de empleo y enriquecen la formación de los estudiantes. Puedes obtener más información sobre los convenios de colaboración en el siguiente enlace: Enlace a los convenios de colaboración del ITTG.',
'¿Cuál es la duración de las carreras en el ITTG?', 'La duración de las carreras en el ITTG varía dependiendo del programa. En general, la mayoría de las carreras tienen una duración de 8 semestres, es decir, 4 años. Sin embargo, algunas carreras pueden tener una duración diferente. Es importante consultar la información específica de cada carrera en el siguiente enlace: Enlace a la duración de las carreras del ITTG.',
'¿El ITTG ofrece posgrados?', 'Sí, el ITTG ofrece programas de posgrado como Maestrías y Doctorados en diferentes áreas del conocimiento. Estos programas están dirigidos a aquellos estudiantes que desean continuar su formación académica y especializarse en un campo específico. Puedes obtener más información sobre los programas de posgrado en el siguiente enlace: Enlace a los programas de posgrado del ITTG.',
'¿El ITTG cuenta con programas de educación continua?', 'Sí, el ITTG ofrece programas de educación continua y cursos de actualización profesional para aquellos interesados en ampliar sus conocimientos y mantenerse actualizados en su campo. Estos programas brindan oportunidades de aprendizaje a lo largo de la vida y permiten a los profesionales mejorar sus habilidades. Puedes obtener más información sobre los programas de educación continua en el siguiente enlace: Enlace a los programas de educación continua del ITTG.',
'¿El ITTG tiene laboratorios especializados?', 'Sí, el ITTG cuenta con laboratorios especializados equipados con tecnología de vanguardia para apoyar la enseñanza y la investigación. Estos laboratorios permiten a los estudiantes realizar prácticas, experimentos y proyectos relacionados con su área de estudio. Puedes obtener más información sobre los laboratorios especializados en el siguiente enlace: Enlace a los laboratorios del ITTG.',
'¿Cuáles son las oportunidades de investigación en el ITTG?', 'El ITTG fomenta la investigación y cuenta con grupos de investigación en diversas áreas. Los estudiantes tienen la oportunidad de participar en proyectos de investigación, colaborar con profesores investigadores y desarrollar habilidades de investigación. Puedes obtener más información sobre las oportunidades de investigación en el siguiente enlace: Enlace a las oportunidades de investigación del ITTG.',
'¿El ITTG tiene programas de emprendimiento?', 'Sí, el ITTG cuenta con programas de emprendimiento que buscan fomentar la creatividad, la innovación y el espíritu empresarial entre los estudiantes. Estos programas brindan apoyo y asesoría para aquellos interesados en desarrollar sus propios proyectos y emprender su propio negocio. Puedes obtener más información sobre los programas de emprendimiento en el siguiente enlace: Enlace a los programas de emprendimiento del ITTG.',
'¿El ITTG ofrece actividades de vinculación con la comunidad?', 'Sí, el ITTG promueve la vinculación con la comunidad a través de diferentes actividades como proyectos sociales, programas de responsabilidad social, servicios comunitarios y más. Estas actividades permiten a los estudiantes contribuir al bienestar de la sociedad y aplicar sus conocimientos en proyectos de impacto social. Puedes obtener más información sobre las actividades de vinculación con la comunidad en el siguiente enlace: Enlace a las actividades de vinculación del ITTG.',
'¿Cuáles son las carreras de ingeniería que ofrece el ITTG?', 'El ITTG ofrece carreras de ingeniería como Ingeniería en Sistemas Computacionales, Ingeniería Electrónica, Ingeniería en Gestión Empresarial, Ingeniería Industrial, Ingeniería Mecatrónica, Ingeniería en Innovación Agrícola Sustentable, entre otras. Cada carrera se enfoca en áreas específicas de conocimiento y brinda una formación integral en su respectivo campo.',
'¿En qué consiste la carrera de Ingeniería en Sistemas Computacionales?', 'La carrera de Ingeniería en Sistemas Computacionales se enfoca en el diseño, desarrollo y mantenimiento de sistemas informáticos. Los estudiantes adquieren conocimientos en programación, bases de datos, redes, seguridad informática y gestión de proyectos. Esta carrera prepara a los estudiantes para trabajar en el desarrollo de software, administración de sistemas y solución de problemas tecnológicos.',
'¿Cuántos salones de clase hay en el ITTG?', 'El ITTG cuenta con una amplia infraestructura que incluye varios salones de clase. El número exacto de salones puede variar, ya que depende de la capacidad y la distribución de cada edificio académico. Sin embargo, la institución cuenta con suficientes salones para atender a la comunidad estudiantil de manera adecuada.',
'¿Cuál es la duración de las carreras en el ITTG?', 'La duración de las carreras en el ITTG varía dependiendo del programa. En general, la mayoría de las carreras tienen una duración de 8 semestres, es decir, 4 años. Algunas carreras pueden tener una duración diferente, como los programas de posgrado. Es importante consultar la información específica de cada carrera para conocer su duración exacta.',
'¿Cómo es el proceso de inscripción en el ITTG?', 'El proceso de inscripción en el ITTG puede variar dependiendo de la convocatoria y el nivel educativo al que se desea ingresar. En general, implica la presentación de documentos, el llenado de una solicitud de inscripción, el pago de las cuotas correspondientes y la entrega de los requisitos establecidos por la institución. Es importante seguir las indicaciones proporcionadas por la institución para completar exitosamente el proceso de inscripción.',
'¿Cómo puedo solicitar una beca en el ITTG?', 'El ITTG cuenta con programas de becas y apoyos financieros para los estudiantes. El proceso de solicitud puede variar según el tipo de beca y los requisitos establecidos. Generalmente, implica la presentación de documentos, el llenado de una solicitud y la participación en el proceso de selección. Es recomendable consultar la convocatoria de becas y seguir las indicaciones proporcionadas por la institución.',
'¿Cuáles son los requisitos para realizar un trámite de titulación en el ITTG?', 'Los requisitos para realizar un trámite de titulación en el ITTG pueden variar según la carrera y el plan de estudios. Algunos requisitos comunes pueden incluir la presentación de documentos, la aprobación de los créditos establecidos, la realización de un proyecto o trabajo de titulación y la obtención de un promedio mínimo. Es importante consultar la normativa y los lineamientos específicos para conocer los requisitos exactos de cada carrera.',
'¿Cuáles son los horarios de atención de la oficina de servicios escolares del ITTG?', 'Los horarios de atención de la oficina de servicios escolares del ITTG pueden variar según la temporada y la disponibilidad de personal. Generalmente, la oficina de servicios escolares opera en horario de oficina, de lunes a viernes. Es recomendable consultar los horarios específicos en la página web oficial del ITTG o comunicarse directamente con la institución para obtener información actualizada.',
'¿Cómo puedo solicitar un cambio de carrera en el ITTG?', 'El proceso de solicitud de cambio de carrera en el ITTG puede variar según las políticas y los cupos disponibles. Generalmente, implica la presentación de una solicitud formal, la justificación del cambio de carrera y la evaluación por parte de las autoridades académicas. Es importante comunicarse con la oficina de servicios escolares del ITTG para obtener información detallada sobre los requisitos y el proceso de solicitud de cambio de carrera.',
'¿Cuál es el procedimiento para solicitar un certificado de estudios en el ITTG?', 'El procedimiento para solicitar un certificado de estudios en el ITTG puede variar según los trámites internos de la institución. Generalmente, implica llenar una solicitud de certificado, presentar una identificación oficial y cubrir las cuotas correspondientes. Es recomendable comunicarse con la oficina de servicios escolares del ITTG para obtener información actualizada y detallada sobre el procedimiento de solicitud de certificado de estudios.',
'¿Cuál es la oferta educativa del ITTG?', 'El ITTG ofrece programas de educación superior en diversas áreas como Ingeniería en Sistemas Computacionales, Ingeniería Electrónica, Ingeniería en Gestión Empresarial, Ingeniería Industrial, Ingeniería Mecatrónica, Ingeniería en Innovación Agrícola Sustentable, y más. Puedes encontrar información detallada sobre la oferta educativa en el siguiente enlace: [Enlace a la oferta educativa del ITTG](enlace).',
'¿Cuál es el perfil de los egresados del ITTG?', 'Los egresados del ITTG se caracterizan por tener una formación sólida en su área de estudio, habilidades técnicas y prácticas, capacidad de trabajo en equipo, liderazgo, pensamiento crítico y habilidades para resolver problemas. Están preparados para enfrentar los retos del mundo laboral y contribuir al desarrollo de la sociedad. Puedes obtener más información sobre el perfil de los egresados en el siguiente enlace: [Enlace al perfil de los egresados del ITTG](enlace).',
'¿El ITTG cuenta con convenios de colaboración con empresas?', 'Sí, el ITTG tiene convenios de colaboración con empresas e instituciones del sector público y privado. Estos convenios permiten establecer vínculos para realizar proyectos conjuntos, prácticas profesionales, programas de capacitación y más. Estos lazos con el sector empresarial brindan oportunidades de empleo y enriquecen la formación de los estudiantes. Puedes obtener más información sobre los convenios de colaboración en el siguiente enlace: [Enlace a los convenios de colaboración del ITTG](enlace).',
'¿Cuál es la duración de las carreras en el ITTG?', 'La duración de las carreras en el ITTG varía dependiendo del programa. En general, la mayoría de las carreras tienen una duración de 8 semestres, es decir, 4 años. Sin embargo, algunas carreras pueden tener una duración diferente. Es importante consultar la información específica de cada carrera en el siguiente enlace: [Enlace a la duración de las carreras del ITTG](enlace).',
'¿El ITTG ofrece posgrados?', 'Sí, el ITTG ofrece programas de posgrado como Maestrías y Doctorados en diferentes áreas del conocimiento. Estos programas están dirigidos a aquellos estudiantes que desean continuar su formación académica y especializarse en un campo específico. Puedes obtener más información sobre los programas de posgrado en el siguiente enlace: [Enlace a los programas de posgrado del ITTG](enlace).',
'¿El ITTG cuenta con programas de educación continua?', 'Sí, el ITTG ofrece programas de educación continua y cursos de actualización profesional para aquellos interesados en ampliar sus conocimientos y mantenerse actualizados en su campo. Estos programas brindan oportunidades de aprendizaje a lo largo de la vida y permiten a los profesionales mejorar sus habilidades. Puedes obtener más información sobre los programas de educación continua en el siguiente enlace: [Enlace a los programas de educación continua del ITTG](enlace).',
'¿El ITTG tiene laboratorios especializados?', 'Sí, el ITTG cuenta con laboratorios especializados equipados con tecnología de vanguardia para apoyar la enseñanza y la investigación. Estos laboratorios permiten a los estudiantes realizar prácticas, experimentos y proyectos relacionados con su área de estudio. Puedes obtener más información sobre los laboratorios especializados en el siguiente enlace: [Enlace a los laboratorios del ITTG](enlace).',
'¿Cuáles son las oportunidades de investigación en el ITTG?', 'El ITTG fomenta la investigación y cuenta con grupos de investigación en diversas áreas. Los estudiantes tienen la oportunidad de participar en proyectos de investigación, colaborar con profesores investigadores y desarrollar habilidades de investigación. Puedes obtener más información sobre las oportunidades de investigación en el siguiente enlace: [Enlace a las oportunidades de investigación del ITTG](enlace).',
'¿El ITTG tiene programas de emprendimiento?', 'Sí, el ITTG cuenta con programas de emprendimiento que buscan fomentar la creatividad, la innovación y el espíritu empresarial entre los estudiantes. Estos programas brindan apoyo y asesoría para aquellos interesados en desarrollar sus propios proyectos y emprender su propio negocio. Puedes obtener más información sobre los programas de emprendimiento en el siguiente enlace: [Enlace a los programas de emprendimiento del ITTG](enlace).',
'¿El ITTG ofrece actividades de vinculación con la comunidad?', 'Sí, el ITTG promueve la vinculación con la comunidad a través de diferentes actividades como proyectos sociales, programas de responsabilidad social, servicios comunitarios y más. Estas actividades permiten a los estudiantes contribuir al bienestar de la sociedad y aplicar sus conocimientos en proyectos de impacto social. Puedes obtener más información sobre las actividades de vinculación con la comunidad en el siguiente enlace: [Enlace a las actividades de vinculación del ITTG](enlace).',
'¿Cuáles son los requisitos para solicitar una residencia profesional en el ITTG?', 'Los requisitos para solicitar una residencia profesional en el ITTG pueden variar según el programa y la normativa interna. Generalmente, los requisitos pueden incluir tener un porcentaje mínimo de créditos aprobados, contar con un promedio académico mínimo, presentar una carta de solicitud, y cumplir con los lineamientos específicos del programa. Es recomendable consultar con la coordinación de residencias profesionales del ITTG para obtener información detallada y actualizada sobre los requisitos y el proceso de solicitud.',
'¿Cuál es el proceso de titulación en el ITTG?', 'El proceso de titulación en el ITTG puede variar según el programa y la modalidad de titulación elegida. Algunas modalidades de titulación disponibles pueden incluir la elaboración de una tesis, la presentación de un examen profesional, la elaboración de un proyecto de investigación o la opción de titulación integral. Es importante consultar la normativa y los lineamientos específicos del programa para conocer los requisitos y el proceso de titulación correspondiente.',
'¿Cuáles son las instalaciones deportivas del ITTG?', 'El ITTG cuenta con instalaciones deportivas que incluyen canchas y espacios adecuados para la práctica de diferentes disciplinas deportivas. Los estudiantes tienen acceso a estas instalaciones para realizar actividades deportivas, entrenamientos y participar en eventos deportivos. Puedes obtener más información sobre las instalaciones deportivas del ITTG en el siguiente enlace: [Enlace a las instalaciones deportivas del ITTG](enlace).',
'¿El ITTG ofrece programas de movilidad estudiantil?', 'Sí, el ITTG ofrece programas de movilidad estudiantil que permiten a los estudiantes realizar intercambios académicos en otras instituciones nacionales e internacionales. Estos programas brindan la oportunidad de vivir una experiencia en otro país, conocer nuevas culturas y enriquecer la formación académica. Puedes obtener más información sobre los programas de movilidad estudiantil en el siguiente enlace: [Enlace a los programas de movilidad estudiantil del ITTG](enlace).',
'¿Cuáles son los requisitos para obtener una cédula profesional en el ITTG?', 'Los requisitos para obtener una cédula profesional en el ITTG pueden variar según la normativa y los trámites establecidos por la Secretaría de Educación Pública (SEP) de México. Generalmente, los requisitos pueden incluir la presentación de documentos como acta de nacimiento, certificado de estudios, título profesional, entre otros. Es recomendable consultar la normativa de la SEP y la oficina de servicios escolares del ITTG para obtener información detallada y actualizada sobre los requisitos y el proceso de obtención de la cédula profesional.',
'¿Cuáles son los servicios de apoyo al estudiante en el ITTG?', 'El ITTG cuenta con diversos servicios de apoyo al estudiante para brindar acompañamiento y asistencia durante su trayectoria académica. Algunos de los servicios disponibles pueden incluir asesoría académica, tutorías, orientación vocacional, servicio médico, servicio psicológico, bolsa de trabajo, entre otros. Puedes obtener más información sobre los servicios de apoyo al estudiante en el siguiente enlace: [Enlace a los servicios de apoyo al estudiante del ITTG](enlace).',
'¿Cuáles son los convenios internacionales del ITTG?', 'El ITTG cuenta con convenios internacionales con instituciones educativas de otros países. Estos convenios permiten el intercambio académico, la colaboración en proyectos de investigación y la internacionalización de la formación de los estudiantes. Puedes obtener más información sobre los convenios internacionales del ITTG en el siguiente enlace: [Enlace a los convenios internacionales del ITTG](enlace).',
'¿El ITTG ofrece programas de tutorías académicas?', 'Sí, el ITTG cuenta con programas de tutorías académicas para brindar apoyo y seguimiento individualizado a los estudiantes. Las tutorías académicas son un espacio de acompañamiento donde los estudiantes pueden recibir orientación, aclarar dudas, fortalecer habilidades y mejorar su desempeño académico. Puedes obtener más información sobre los programas de tutorías académicas en el siguiente enlace: [Enlace a los programas de tutorías académicas del ITTG](enlace).',
'¿Cuál es la política de inclusión y diversidad del ITTG?', 'El ITTG promueve una política de inclusión y diversidad que busca garantizar la igualdad de oportunidades y el respeto a la diversidad en su comunidad estudiantil. Se busca crear un ambiente inclusivo donde todos los estudiantes sean valorados y puedan desarrollarse plenamente. Puedes obtener más información sobre la política de inclusión y diversidad del ITTG en el siguiente enlace: [Enlace a la política de inclusión y diversidad del ITTG](enlace).',
'¿El ITTG ofrece programas de educación a distancia?', 'Sí, el ITTG ofrece programas de educación a distancia que permiten a los estudiantes cursar sus estudios de forma virtual, sin necesidad de asistir físicamente a la institución. Estos programas brindan flexibilidad y acceso a la educación a personas que no pueden asistir presencialmente. Puedes obtener más información sobre los programas de educación a distancia en el siguiente enlace: [Enlace a los programas de educación a distancia del ITTG](enlace).',
'¿El ITTG cuenta con una biblioteca?', 'Sí, el ITTG cuenta con una biblioteca que ofrece una amplia colección de libros, revistas, recursos digitales y otros materiales de consulta. Los estudiantes tienen acceso a la biblioteca para realizar investigaciones, estudiar y ampliar sus conocimientos. Puedes obtener más información sobre la biblioteca del ITTG en el siguiente enlace: [Enlace a la biblioteca del ITTG](enlace).',
'¿Cuál es el proceso de admisión al ITTG?', 'El proceso de admisión al ITTG puede variar según el programa y la convocatoria vigente. Generalmente, implica la presentación de una solicitud de admisión, la realización de un examen de admisión, la entrega de documentación requerida y la evaluación de los resultados. Es importante estar pendiente de las fechas y requisitos establecidos en la convocatoria. Puedes obtener más información sobre el proceso de admisión en el siguiente enlace: [Enlace al proceso de admisión del ITTG](enlace).',
'¿El ITTG ofrece becas o apoyos económicos?', 'Sí, el ITTG cuenta con programas de becas y apoyos económicos para estudiantes destacados o con necesidades económicas. Estos programas buscan brindar oportunidades de acceso y permanencia en la institución. Puedes obtener más información sobre las becas y apoyos económicos en el siguiente enlace: [Enlace a las becas y apoyos económicos del ITTG](enlace).',
'¿Cuáles son las actividades culturales y artísticas en el ITTG?', 'El ITTG ofrece actividades culturales y artísticas que permiten a los estudiantes explorar y desarrollar su creatividad. Estas actividades incluyen presentaciones de teatro, música, danza, exposiciones artísticas, concursos, entre otros. Puedes obtener más información sobre las actividades culturales y artísticas en el siguiente enlace: [Enlace a las actividades culturales y artísticas del ITTG](enlace).',
'¿El ITTG cuenta con programas de apoyo a emprendedores?', 'Sí, el ITTG cuenta con programas de apoyo a emprendedores que buscan fomentar el espíritu empresarial y apoyar el desarrollo de proyectos innovadores. Estos programas brindan asesoría, capacitación y recursos para aquellos interesados en iniciar su propio negocio. Puedes obtener más información sobre los programas de apoyo a emprendedores en el siguiente enlace: [Enlace a los programas de apoyo a emprendedores del ITTG](enlace).',
'¿Cuáles son los requisitos para solicitar una beca en el ITTG?', 'Los requisitos para solicitar una beca en el ITTG pueden variar según el tipo de beca y la convocatoria vigente. Generalmente, los requisitos pueden incluir contar con un buen desempeño académico, presentar documentos que demuestren la situación económica del estudiante, cumplir con los lineamientos establecidos y participar en el proceso de selección. Es importante consultar las convocatorias y los requisitos específicos para cada beca. Puedes obtener más información sobre las becas en el siguiente enlace: [Enlace a las becas del ITTG](enlace).',
'¿Cuál es la ubicación del ITTG?', 'El ITTG se encuentra ubicado en la ciudad de Tepic, Nayarit, México. Su dirección es: [Dirección del ITTG](dirección).',
'¿El ITTG ofrece programas de intercambio internacional?', 'Sí, el ITTG ofrece programas de intercambio internacional que permiten a los estudiantes estudiar en instituciones educativas de otros países. Estos programas brindan la oportunidad de vivir una experiencia multicultural, mejorar el dominio de un idioma extranjero y ampliar horizontes académicos. Puedes obtener más información sobre los programas de intercambio internacional en el siguiente enlace: [Enlace a los programas de intercambio internacional del ITTG](enlace).',
'¿El ITTG cuenta con servicios de orientación vocacional?', 'Sí, el ITTG cuenta con servicios de orientación vocacional que brindan apoyo a los estudiantes en la elección de su carrera profesional. Estos servicios ofrecen asesoría personalizada, evaluaciones de aptitudes y habilidades, y herramientas para ayudar a los estudiantes a tomar decisiones informadas sobre su futuro profesional. Puedes obtener más información sobre los servicios de orientación vocacional en el siguiente enlace: [Enlace a los servicios de orientación vocacional del ITTG](enlace).',
'¿El ITTG tiene programas de educación dual?', 'Sí, el ITTG cuenta con programas de educación dual que combinan la formación académica con la experiencia laboral. Estos programas permiten a los estudiantes trabajar en empresas mientras estudian, lo que les brinda la oportunidad de aplicar sus conocimientos en un entorno real de trabajo y adquirir experiencia profesional. Puedes obtener más información sobre los programas de educación dual en el siguiente enlace: [Enlace a los programas de educación dual del ITTG](enlace).',
'¿El ITTG ofrece servicios de apoyo psicológico?', 'Sí, el ITTG cuenta con servicios de apoyo psicológico para brindar atención y acompañamiento a los estudiantes en temas relacionados con su bienestar emocional y psicológico. Estos servicios ofrecen asesoría, terapia y actividades de promoción de la salud mental. Puedes obtener más información sobre los servicios de apoyo psicológico en el siguiente enlace: [Enlace a los servicios de apoyo psicológico del ITTG](enlace).',
'¿El ITTG cuenta con programas de educación inclusiva?', 'Sí, el ITTG cuenta con programas de educación inclusiva que buscan garantizar el acceso y la participación de todas las personas, independientemente de sus condiciones o necesidades especiales. Estos programas promueven la igualdad de oportunidades y la adaptación de los entornos educativos para asegurar la inclusión de todos los estudiantes. Puedes obtener más información sobre los programas de educación inclusiva en el siguiente enlace: [Enlace a los programas de educación inclusiva del ITTG](enlace).',
'¿El ITTG ofrece programas de posgrado?', 'Sí, el ITTG ofrece programas de posgrado en diferentes áreas del conocimiento. Los programas de posgrado incluyen maestrías y doctorados, y brindan la oportunidad de especializarse en una disciplina específica y desarrollar habilidades de investigación. Puedes obtener más información sobre los programas de posgrado en el siguiente enlace: [Enlace a los programas de posgrado del ITTG](enlace).',
'¿Cuál es la duración de los programas de estudios en el ITTG?', 'La duración de los programas de estudios en el ITTG puede variar según el nivel y el tipo de programa. Por lo general, las licenciaturas tienen una duración de cuatro años, las maestrías pueden durar de uno a dos años, y los doctorados pueden durar de tres a cinco años, dependiendo de la disciplina. Es importante consultar los planes de estudio y los requisitos específicos de cada programa. Puedes obtener más información sobre la duración de los programas de estudios en el siguiente enlace: [Enlace a la duración de los programas de estudios del ITTG](enlace).',
'¿El ITTG cuenta con programas de educación continua?', 'Sí, el ITTG cuenta con programas de educación continua que ofrecen capacitación y actualización profesional en áreas específicas. Estos programas están dirigidos a profesionales en ejercicio que desean ampliar sus conocimientos y adquirir nuevas habilidades. Puedes obtener más información sobre los programas de educación continua en el siguiente enlace: [Enlace a los programas de educación continua del ITTG](enlace).',
'¿Cuáles son las áreas de investigación del ITTG?', 'El ITTG cuenta con áreas de investigación en diversas disciplinas, como ingeniería, tecnología, ciencias de la computación, ciencias naturales, ciencias sociales, entre otros. Las áreas de investigación pueden incluir temas como energías renovables, materiales avanzados, sistemas inteligentes, desarrollo de software, biotecnología, entre otros. Puedes obtener más información sobre las áreas de investigación en el siguiente enlace: [Enlace a las áreas de investigación del ITTG](enlace).',
'¿El ITTG ofrece programas de educación en línea?', 'Sí, el ITTG ofrece programas de educación en línea que permiten a los estudiantes cursar sus estudios de manera virtual, a través de plataformas educativas y recursos en línea. Estos programas brindan flexibilidad de horarios y acceso a la educación desde cualquier ubicación. Puedes obtener más información sobre los programas de educación en línea en el siguiente enlace: [Enlace a los programas de educación en línea del ITTG](enlace).',
'¿El ITTG tiene convenios con empresas o industrias?', 'Sí, el ITTG cuenta con convenios con empresas e industrias que permiten la vinculación y colaboración entre la institución y el sector empresarial. Estos convenios pueden incluir programas de prácticas profesionales, proyectos conjuntos de investigación, apoyo para el desarrollo de proyectos de emprendimiento, entre otros. Puedes obtener más información sobre los convenios con empresas e industrias en el siguiente enlace: [Enlace a los convenios del ITTG con empresas e industrias](enlace).',
'¿Cuáles son los idiomas que se enseñan en el ITTG?', 'El ITTG ofrece la enseñanza de idiomas como parte de su oferta académica. Los idiomas que se enseñan pueden variar, pero generalmente incluyen el inglés como lengua extranjera. Además, es posible que se ofrezcan cursos de otros idiomas según la demanda y los recursos disponibles. Es recomendable consultar la oferta de idiomas del ITTG para obtener información actualizada. Puedes obtener más información sobre la enseñanza de idiomas en el siguiente enlace: [Enlace a la enseñanza de idiomas en el ITTG](enlace).',
'¿El ITTG cuenta con laboratorios de investigación?', 'Sí, el ITTG cuenta con laboratorios de investigación equipados con tecnología y recursos necesarios para llevar a cabo investigaciones en diversas áreas. Estos laboratorios brindan un espacio adecuado para la experimentación, el análisis y el desarrollo de proyectos científicos. Puedes obtener más información sobre los laboratorios de investigación del ITTG en el siguiente enlace: [Enlace a los laboratorios de investigación del ITTG](enlace).',
'¿El ITTG tiene programas de intercambio nacional?', 'Sí, el ITTG ofrece programas de intercambio nacional que permiten a los estudiantes realizar estancias académicas en otras instituciones educativas dentro de México. Estos programas brindan la oportunidad de conocer otras culturas, ampliar la red de contactos y enriquecer la formación académica. Puedes obtener más información sobre los programas de intercambio nacional en el siguiente enlace: [Enlace a los programas de intercambio nacional del ITTG](enlace).',
'¿El ITTG cuenta con programas de tutorías personalizadas?', 'Sí, el ITTG cuenta con programas de tutorías personalizadas que ofrecen apoyo individualizado a los estudiantes. Estas tutorías brindan acompañamiento académico, orientación en el proceso de aprendizaje y ayuda para superar dificultades. Puedes obtener más información sobre los programas de tutorías personalizadas en el siguiente enlace: [Enlace a los programas de tutorías personalizadas del ITTG](enlace).',
'¿Cuáles son las opciones de transporte para llegar al ITTG?', 'Para llegar al ITTG, puedes utilizar diferentes opciones de transporte, como transporte público (autobús, taxi), transporte privado (automóvil, motocicleta) o incluso bicicleta o caminar, dependiendo de tu ubicación y preferencias. Es recomendable consultar con antelación las rutas de transporte disponibles y planificar tu viaje según tus necesidades.'
]
# Agrega más preguntas y respuestas aquí


# Entrenar el chatbot con preguntas y respuestas manualmente
list_trainer = ListTrainer(bot)
for pregunta, respuesta in preguntas_respuestas:
    list_trainer.train([pregunta, respuesta])

# Vista de la página de inicio
def index(request):
    return render(request, 'chat/index.html')

# Vista para una ruta específica
def specific(request):
    number = 55
    return HttpResponse(number)

# Vista para obtener una respuesta del chatbot
def getResponse(request):
    userMessage = request.GET.get('userMessage')
    chatResponse = str(bot.get_response(userMessage))
    return HttpResponse(chatResponse)
